FROM crr0004/awsjplosr:latest

RUN wget -qO - http://repo.radeon.com/rocm/apt/debian/rocm.gpg.key | apt-key add -
RUN echo "deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main" | tee /etc/apt/sources.list.d/rocm.list


RUN apt-get update -y && apt-get install -y rocm-dev rocm-libs miopen-hip cxlactivitylogger rccl python3-dev libelf1
RUN pip3 uninstall -y tensorflow && pip3 install "tensorflow-rocm==1.14.5"

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["./run.sh mars_full_sim.launch"]
